export enum ActionType {
    GET_POPULAR_TAGS = '[POPULAR_TAGS] GET_POPULAR_TAGS',
    GET_POPULAR_TAGS_SUCCESS = '[POPULAR_TAGS] GET_POPULAR_TAGS_SUCCESS',
    GET_POPULAR_TAGS_FAILURE = '[POPULAR_TAGS] GET_POPULAR_TAGS_FAILURE'
}
