export enum ActionType {
    GET_POPULAR_TAGS = '[Tags] GET_POPULAR_TAGS',
    GET_POPULAR_TAGS_SUCCESS = '[Tags] GET_POPULAR_TAGS_SUCCESS',
    GET_POPULAR_TAGS_FAILURE = '[Tags] GET_POPULAR_TAGS_FAILURE'
}
