export enum ActionTypes {
  UPDATE_ARTICLE = '[UPDATE_ARTICLE] UPDATE_ARTICLE',
  UPDATE_ARTICLE_SUCCESS = '[UPDATE_ARTICLE] UPDATE_ARTICLE_SUCCESS',
  UPDATE_ARTICLE_FAILURE = '[UPDATE_ARTICLE] UPDATE_ARTICLE_FAILURE',

  GET_ARTICLE = '[UPDATE_ARTICLE] GET_ARTICLE',
  GET_ARTICLE_SUCCESS = '[UPDATE_ARTICLE] GET_ARTICLE_SUCCESS',
  GET_ARTICLE_FAILURE = '[UPDATE_ARTICLE] GET_ARTICLE_FAILURE',
}
