export enum ActionTypes {
  GET_PROFILE = '[User Profile] GET_PROFILE',
  GET_PROFILE_SUCCESS = '[User Profile] GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE = '[User Profile] GET_PROFILE_FAILURE',
  FOLLOW_PROFILE = '[User Profile] FOLLOW_PROFILE',
  FOLLOW_PROFILE_SUCCESS = '[User Profile] FOLLOW_PROFILE_SUCCESS',
  FOLLOW_PROFILE_FAILURE = '[User Profile] FOLLOW_PROFILE_FAILURE',
}
